### ISSUE TITLE
[BUG] Unable to log in with Github

### ISSUE THREAD

**Issue by OlexG** [cookiedb/cloud-feedback#2] opened 2023-01-30 16:36 UTC
**Describe the bug**
Unable to log in or sign-up with Github

**To Reproduce**
1. Login with Github

**Expected behavior**
User is redirected back to the page logged in

**Screenshots**
<img width="826" alt="Screen Shot 2023-01-30 at 8 35 08 AM" src="https://user-images.githubusercontent.com/36348190/215537985-4b0fce21-dec1-4557-a769-5e2991f791ad.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version: x.x where x is can be any number between 0 and 100 :) (I don't know the version)

**Comment by OlexG** [comment] 2023-01-30 16:37
FYI, looks like logging in with Gitlab worked

**Comment by lino-levan** [comment] 2023-01-30 17:27
Very interesting bug, will look into it. It looks like there is a null value for something that shouldn't be null coming from Github's side.

**Comment by lino-levan** [comment] 2023-01-30 19:04
This has been fixed in the latest release. The issue is that you don't have a nickname set but you do have a username. Now the code falls back to using your username if the user doesn't have a nickname.

**Closed as completed by lino-levan** 2023-01-30 19:04 UTC
Labels: bug
